export enum RoutesEnum {
  HOME = "/",
  TYPE = "/type",
  MAIN = "/main",
  BURGERS = "/burger",
  PERSONALIZE = "/personalize",
  CHICKEN = "/chicken",
  NUGGETS = "/nuggets",
  AVATAR = "/avatar",
  FRIES = "/fries",
  HAPPY_MEAL = "/happy-meal",
  CHECKOUT = "/checkout",
  QR = "/qr",
  DEDO = "/dedo",
}
